workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Key"
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Fetch and Auto-Create Signing Files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.swaziapplilab.noq" --type IOS_APP_STORE --create
          keychain add-certificates
          cd ios/App
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          cd ios/App
          xcode-project build-ipa --project "App.xcodeproj" --scheme "App"
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
