workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    integrations:
      app_store_connect: "Codemagic Key"
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.swaziapplilab.noq" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
