workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.swaziapplilab.noq
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS App
        script: |
          cd ios/App
          xcodebuild build -workspace App.xcworkspace -scheme App -destination generic/platform=iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
